import { afterEach, describe, expect, it, vi } from "vitest";
import { GmailProvider, insertPixel } from "../src/providers/gmail/gmail";

afterEach(()=>{document.body.innerHTML="";location.hash=""});
describe("Gmail integration",()=>{
  it("inserts exactly one loadable invisible tracking pixel",()=>{const body=document.createElement("div");insertPixel(body,"https://api.example/t/abc.gif");insertPixel(body,"https://api.example/t/abc.gif");const pixels=body.querySelectorAll("img[data-opentrackmail-pixel]");expect(pixels).toHaveLength(1);expect((pixels[0] as HTMLImageElement).style.width).toBe("1px");expect((pixels[0] as HTMLImageElement).style.opacity).toBe("0")});
  it("detects dynamic compose windows and places a small toggle after Gmail's send group",async()=>{const provider=new GmailProvider(vi.fn(),async()=>true);provider.start();document.body.innerHTML=`<div role="dialog"><div role="textbox" contenteditable="true"></div><input name="subjectbox"><div email="a@example.com"></div><div class="send-group"><button role="button" aria-label="Send">Send</button><button aria-label="More send options"></button></div></div>`;await new Promise(resolve=>setTimeout(resolve,20));const toggle=document.querySelector<HTMLButtonElement>(".otm-track-toggle");const group=document.querySelector(".send-group");expect(toggle).not.toBeNull();expect(toggle?.textContent).toBe("✓✓");expect(toggle?.getAttribute("aria-pressed")).toBe("true");expect(group?.contains(toggle || null)).toBe(false);expect(group?.nextElementSibling?.classList.contains("otm-compose-control")).toBe(true);provider.stop()});
  it("pauses send, waits for protected tracking, inserts the pixel, then resumes Gmail",async()=>{let release!:()=>void;const protectedTracking=new Promise<{email:{id:string;subject:string;recipients:string[];sentAt:string;providerMessageId:null;providerThreadId:null;openCount:number;firstOpenedAt:null;lastOpenedAt:null;status:"sent"};pixelUrl:string}>(resolve=>{release=()=>resolve({email:{id:"1",subject:"Hello",recipients:["a@example.com"],sentAt:new Date().toISOString(),providerMessageId:null,providerThreadId:null,openCount:0,firstOpenedAt:null,lastOpenedAt:null,status:"sent"},pixelUrl:"https://api.example/t/token.gif"})});const onSend=vi.fn().mockReturnValue(protectedTracking);const provider=new GmailProvider(onSend,async()=>true);document.body.innerHTML=`<div role="dialog"><div role="textbox" contenteditable="true">Body</div><input name="subjectbox" value="Hello"><div email="a@example.com"></div><div><button role="button" aria-label="Send">Send</button></div></div>`;provider.start();await new Promise(resolve=>setTimeout(resolve,20));const send=document.querySelector<HTMLButtonElement>("[aria-label='Send']")!;const delivered=vi.fn();send.addEventListener("click",delivered);send.click();await new Promise(resolve=>setTimeout(resolve,10));expect(onSend).toHaveBeenCalledOnce();expect(delivered).not.toHaveBeenCalled();expect(document.querySelectorAll("img[data-opentrackmail-pixel]")).toHaveLength(0);release();await new Promise(resolve=>setTimeout(resolve,20));expect(delivered).toHaveBeenCalledOnce();expect(document.querySelectorAll("img[data-opentrackmail-pixel]")).toHaveLength(1);provider.stop()});
  it("reuses the tracking ID after a failed registration and shows the error",async()=>{const onSend=vi.fn().mockRejectedValueOnce(new Error("Pixel server unavailable")).mockRejectedValueOnce(new Error("Pixel server unavailable"));const provider=new GmailProvider(onSend,async()=>true);document.body.innerHTML=`<div role="dialog"><div role="textbox" contenteditable="true">Body</div><input name="subjectbox" value="Hello"><div email="a@example.com"></div><div><button role="button" aria-label="Send">Send</button></div></div>`;provider.start();await new Promise(resolve=>setTimeout(resolve,20));const send=document.querySelector<HTMLButtonElement>("[aria-label='Send']")!;send.click();await new Promise(resolve=>setTimeout(resolve,10));expect(document.querySelector(".otm-compose-error")?.textContent).toBe("Pixel server unavailable");send.click();await new Promise(resolve=>setTimeout(resolve,10));expect(onSend).toHaveBeenCalledTimes(2);expect(onSend.mock.calls[0]![1]).toBe(onSend.mock.calls[1]![1]);provider.stop()});
  it("updates Sent rows without duplicate status icons",()=>{location.hash="#sent";document.body.innerHTML=`<div role="main"><table><tbody><tr><td><a href="#sent/thread-1"><span>Project update</span></a></td><td></td></tr></tbody></table></div>`;const provider=new GmailProvider(vi.fn(),async()=>true);const email={id:"1",subject:"Project update",recipients:["a@example.com"],sentAt:"2026-09-14T16:00:00Z",providerMessageId:null,providerThreadId:"thread-1",openCount:2,firstOpenedAt:"2026-09-14T16:01:00Z",lastOpenedAt:"2026-09-14T16:03:00Z",status:"opened" as const};provider.renderStatuses([email]);provider.renderStatuses([email]);expect(document.querySelectorAll(".otm-row-status")).toHaveLength(1);expect(document.querySelector(".otm-row-status")?.textContent).toBe("✓✓")});
});
