import type { StoredEmail } from "../../types";
import type { WebmailProvider, ComposeSnapshot } from "../provider";
import { gmailSelectors as s } from "./selectors";

type SendResult={email:StoredEmail;pixelUrl:string};
type ComposeState={enabled:boolean;control:HTMLButtonElement;error:HTMLSpanElement};
export class GmailProvider implements WebmailProvider{
  private observer?:MutationObserver;private composeStates=new WeakMap<Element,ComposeState>();private bypass=new WeakSet<Element>();private emails:StoredEmail[]=[];private scanQueued=false;private associations=new Set<string>();
  constructor(private readonly onSend:(snapshot:ComposeSnapshot,clientMessageId:string)=>Promise<SendResult>,private readonly defaultTracking:()=>Promise<boolean>,private readonly onAssociate?:(id:string,threadId:string)=>Promise<StoredEmail>){}
  start(){this.observer=new MutationObserver(()=>this.queueScan());this.observer.observe(document.body,{childList:true,subtree:true});document.addEventListener("click",this.captureSend,true);document.addEventListener("keydown",this.captureShortcut,true);this.queueScan()}
  stop(){this.observer?.disconnect();document.removeEventListener("click",this.captureSend,true);document.removeEventListener("keydown",this.captureShortcut,true)}
  renderStatuses(emails:StoredEmail[]){this.emails=emails;this.scanSentRows()}
  private queueScan(){if(this.scanQueued)return;this.scanQueued=true;requestAnimationFrame(()=>{this.scanQueued=false;this.scanComposes();this.scanSentRows()})}
  private scanComposes(){document.querySelectorAll(s.compose).forEach(compose=>{if(this.composeStates.has(compose))return;const send=compose.querySelector<HTMLElement>(s.send);if(!send)return;this.installToggle(compose,send)})}
  private async installToggle(compose:Element,send:HTMLElement){const enabled=await this.defaultTracking();if(!compose.isConnected||this.composeStates.has(compose))return;const wrap=document.createElement("span");wrap.className="otm-compose-control";const button=document.createElement("button");button.type="button";button.className="otm-track-toggle";button.setAttribute("aria-pressed",String(enabled));button.innerHTML=`<span aria-hidden="true">✓✓</span>`;const error=document.createElement("span");error.className="otm-compose-error";error.setAttribute("role","status");wrap.append(button,error);placeComposeControl(send,wrap);const state={enabled,control:button,error};this.composeStates.set(compose,state);this.paintToggle(state);button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();state.enabled=!state.enabled;this.paintToggle(state)})}
  private paintToggle(state:ComposeState){state.control.classList.toggle("is-on",state.enabled);state.control.setAttribute("aria-pressed",String(state.enabled));const label=state.enabled?"Tracking enabled for this email":"Tracking disabled for this email";state.control.setAttribute("aria-label",label);state.control.title=label}
  private captureSend=(event:Event)=>{const target=event.target as Element|null;const send=target?.closest?.(s.send);if(!send||this.bypass.has(send))return;const compose=send.closest(s.compose);if(!compose)return;const state=this.composeStates.get(compose);if(!state?.enabled)return;event.preventDefault();event.stopImmediatePropagation();void this.trackThenSend(compose,send,state)};
  private captureShortcut=(event:KeyboardEvent)=>{if(!(event.key==="Enter"&&(event.ctrlKey||event.metaKey)))return;const target=event.target as Element|null;const compose=target?.closest?.(s.compose);if(!compose)return;const send=compose.querySelector<HTMLElement>(s.send);const state=this.composeStates.get(compose);if(!send||!state?.enabled)return;event.preventDefault();event.stopImmediatePropagation();void this.trackThenSend(compose,send,state)};
  private async trackThenSend(compose:Element,send:Element,state:ComposeState){if(state.control.disabled)return;state.control.disabled=true;state.control.classList.remove("has-error");state.error.textContent="";this.paintToggle(state);try{const snapshot=this.readCompose(compose,send as HTMLElement);if(!snapshot.recipients.length)throw new Error("Add a recipient before sending");const result=await this.onSend(snapshot,crypto.randomUUID());insertPixel(snapshot.body,result.pixelUrl);this.emails=[result.email,...this.emails.filter(email=>email.id!==result.email.id)];this.bypass.add(send);(send as HTMLElement).click();queueMicrotask(()=>this.bypass.delete(send))}catch(error){state.error.textContent=error instanceof Error?error.message:"Tracking could not be added";state.control.classList.add("has-error");state.control.title=state.error.textContent}finally{state.control.disabled=false}}
  private readCompose(compose:Element,sendButton:HTMLElement):ComposeSnapshot{const body=compose.querySelector<HTMLElement>(s.body);if(!body)throw new Error("Message body not found");const subject=compose.querySelector<HTMLInputElement>(s.subject)?.value.trim()||"(no subject)";const recipients=Array.from(compose.querySelectorAll<HTMLElement>(s.recipients)).map(node=>node.getAttribute("email")||"").filter((email,index,all)=>email&&all.indexOf(email)===index);return{subject,recipients,body,sendButton}}
  private scanSentRows(){if(!isSentView())return;for(const row of document.querySelectorAll<HTMLElement>(s.rows)){const existing=row.querySelector<HTMLElement>(".otm-row-status");const subject=readRowSubject(row);const threadId=readThreadId(row);const match=this.emails.find(email=>(threadId&&email.providerThreadId===threadId)||email.subject===subject);if(!match){existing?.remove();continue}if(threadId&&!match.providerThreadId&&this.onAssociate){const key=`${match.id}:${threadId}`;if(!this.associations.has(key)){this.associations.add(key);void this.onAssociate(match.id,threadId).then(updated=>{this.emails=this.emails.map(email=>email.id===updated.id?updated:email);this.queueScan()}).catch(()=>this.associations.delete(key))}}if(!existing){const icon=document.createElement("span");icon.className="otm-row-status";row.lastElementChild?.prepend(icon);this.paintStatus(icon,match)}else this.paintStatus(existing,match)}}
  private paintStatus(icon:HTMLElement,email:StoredEmail){const opened=email.openCount>0;icon.textContent=opened?"✓✓":"✓";icon.classList.toggle("is-opened",opened);icon.dataset.emailId=email.id;icon.setAttribute("aria-label",tooltip(email));icon.title=tooltip(email)}
}
export function placeComposeControl(send:HTMLElement,control:HTMLElement){const possibleSendGroup=send.parentElement;const anchor=possibleSendGroup&&possibleSendGroup.childElementCount<=4?possibleSendGroup:send;anchor.insertAdjacentElement("afterend",control)}
export function insertPixel(body:HTMLElement,pixelUrl:string){if(body.querySelector("img[data-opentrackmail-pixel]"))return;const pixel=document.createElement("img");pixel.src=pixelUrl;pixel.alt="";pixel.width=1;pixel.height=1;pixel.dataset.opentrackmailPixel="true";pixel.setAttribute("aria-hidden","true");pixel.style.cssText="width:1px!important;height:1px!important;border:0!important;opacity:0!important;overflow:hidden!important;line-height:0!important";body.append(pixel)}
function isSentView(){return /(?:#|\/)sent(?:\/|$)/.test(location.hash)||location.hash.includes("#sent")}
function readRowSubject(row:Element){return row.querySelector<HTMLElement>(s.subjectInRow)?.textContent?.trim()||""}
function readThreadId(row:Element){const href=row.querySelector<HTMLAnchorElement>(s.threadLink)?.getAttribute("href")||"";return href.match(/(?:#|\/)sent\/([^/?]+)/)?.[1]||row.getAttribute("data-legacy-thread-id")||null}
function tooltip(email:StoredEmail){if(!email.openCount)return`Tracking active\nNo open detected\nSent: ${format(email.sentAt)}`;return`Opened ${email.openCount} ${email.openCount===1?"time":"times"}\nFirst: ${format(email.firstOpenedAt)}\nLast: ${format(email.lastOpenedAt)}`}
function format(value:string|null){return value?new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)):"Unknown"}
