import "./style.css";
import type { ExtensionState, BackgroundMessage, StoredEmail } from "../types";
const appUrl=import.meta.env.VITE_APP_URL||"http://localhost:3001/app";
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
async function message<T>(payload:BackgroundMessage):Promise<T>{const result=await chrome.runtime.sendMessage(payload) as {ok:boolean;value?:T;error?:string};if(!result.ok)throw new Error(result.error);return result.value as T}
async function load(){try{render(await message<ExtensionState>({type:"GET_STATE"}))}catch(error){showError(error)}}
function render(state:ExtensionState){el("signed-out").hidden=Boolean(state.session);el("signed-in").hidden=!state.session;el("sign-out").hidden=!state.session;if(!state.session)return;const email=el<HTMLAnchorElement>("account-email");email.textContent=state.session.user.email;email.href=`mailto:${state.session.user.email}`;const toggle=el<HTMLButtonElement>("tracking-toggle");toggle.classList.toggle("on",state.defaultTracking);toggle.setAttribute("aria-checked",String(state.defaultTracking));const list=el("recent-list");list.replaceChildren(...(state.recent.length?state.recent.slice(0,5).map(recentRow):[emptyRow()]))}
function recentRow(email:StoredEmail){const row=document.createElement("div");row.className="recent-row";const recipient=email.recipients[0]?.split("@")[0]||"Recipient";row.innerHTML=`<div><b></b><span></span></div><small class="${email.openCount?"opened":""}"></small>`;const text=row.querySelector("div")!;text.querySelector("b")!.textContent=recipient;text.querySelector("span")!.textContent=email.subject;const status=row.querySelector("small")!;status.textContent=email.openCount?`✓✓ Opened ${relative(email.lastOpenedAt)}`:`✓ Sent ${relative(email.sentAt)}`;return row}
function emptyRow(){const div=document.createElement("p");div.className="empty";div.textContent="No tracked emails yet.";return div}
function relative(value:string|null){if(!value)return"";const mins=Math.max(1,Math.round((Date.now()-new Date(value).getTime())/60000));if(mins<60)return`${mins} min ago`;const hours=Math.round(mins/60);return hours<24?`${hours} hr ago`:`${Math.round(hours/24)} d ago`}
function showError(error:unknown){el("error").textContent=error instanceof Error?error.message:"Something went wrong"}
el("sign-in").addEventListener("click",async()=>{el<HTMLButtonElement>("sign-in").disabled=true;try{await message({type:"AUTH_SIGN_IN"});await load()}catch(error){showError(error)}finally{el<HTMLButtonElement>("sign-in").disabled=false}});el("sign-out").addEventListener("click",async()=>{await message({type:"AUTH_SIGN_OUT"});await load()});el("tracking-toggle").addEventListener("click",async()=>{const state=await message<ExtensionState>({type:"GET_STATE"});render(await message<ExtensionState>({type:"SET_DEFAULT_TRACKING",value:!state.defaultTracking}))});el("dashboard").addEventListener("click",()=>chrome.tabs.create({url:`${appUrl}/emails`}));el("settings").addEventListener("click",()=>chrome.tabs.create({url:`${appUrl}/settings`}));void load();
